import {FormGroup, Validators} from '@angular/forms';
import {FormRolPagoEnum} from './form-rol-pago.enum';
import {fieldType, FormField} from "../../../componentes/forms/interfaces/form-field";

export const FORM_ROL_PAGO: () => (FormField[]) = () => {
  const arregloCampos: FormField[] = [
    {
      label: 'Periodo laboral',
      placeholder: 'Ej: Ene - 2022',
      help: 'Seleccione un usuario',
      formControlName: FormRolPagoEnum.idPeriodoLaboral,
      initialValue: '',
      validators: [
        Validators.required,
      ],
      type: fieldType.autoComplete,
      formGroup: new FormGroup({}),
      valid: false,
      column: '6',
      actualValue: '',
      autoComplete: {
        field: 'detalle',
        inputId: 'id',
        suggestions: []
      }
    },
    {
      label: 'Historial laboral',
      placeholder: 'Ej:',
      help: 'Seleccione un usuario',
      formControlName: FormRolPagoEnum.idHistorialLaboral,
      initialValue: '',
      validators: [
        Validators.required,
      ],
      type: fieldType.autoComplete,
      formGroup: new FormGroup({}),
      valid: false,
      column: '6',
      actualValue: '',
      autoComplete: {
        field: 'detalle',
        inputId: 'id',
        suggestions: []
      }
    },
    {
      type: fieldType.date,
      label: 'Fecha desde',
      formControlName: FormRolPagoEnum.fechaDesde,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese la fecha desde',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      formGroup: new FormGroup({}),
      valid: false,
      column: '6',
      actualValue: '',
    },
    {
      type: fieldType.date,
      label: 'Fecha hasta',
      formControlName: FormRolPagoEnum.fechaHasta,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese la fecha hasta',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      formGroup: new FormGroup({}),
      valid: false,
      column: '6',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Horas 25',
      formControlName: FormRolPagoEnum.horas25,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese las horas 25',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 0,
        maxFractionDigits: 0
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Horas 50',
      formControlName: FormRolPagoEnum.horas50,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese las horas 50',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 0,
        maxFractionDigits: 0
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Horas 100',
      formControlName: FormRolPagoEnum.horas100,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese las horas 100',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 0,
        maxFractionDigits: 0
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Retenciones judiciales',
      formControlName: FormRolPagoEnum.retencionesJudiciales,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese las retenciones judiciales',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Poliza personal',
      formControlName: FormRolPagoEnum.polizaPersonal,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese la poliza personal',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Aporte IESS',
      formControlName: FormRolPagoEnum.aporteIess,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el aporte IESS',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Impuesto renta',
      formControlName: FormRolPagoEnum.impuestoRenta,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el impuesto renta',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Descuento por atrasos',
      formControlName: FormRolPagoEnum.descuentosPorAtrasos,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el descuento por atraso',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Anticipos',
      formControlName: FormRolPagoEnum.anticipos,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese los anticipos',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Multas',
      formControlName: FormRolPagoEnum.multas,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese las multas',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Otros descuentos',
      formControlName: FormRolPagoEnum.otrosDescuentos,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese si tiene otros descuentos',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Celular consumo',
      formControlName: FormRolPagoEnum.celularConsumo,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el consumo celular',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Permiso horas',
      formControlName: FormRolPagoEnum.permisoHoras,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese las horas de permiso ',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Permiso días',
      formControlName: FormRolPagoEnum.permisoDias,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese los días de permiso ',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Descuentos por faltas',
      formControlName: FormRolPagoEnum.descuentosPorFaltas,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el descuento por faltas',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Ley solidaria',
      formControlName: FormRolPagoEnum.leySolidaria,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el descuento por la ley solidaria',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Prestamos empresa',
      formControlName: FormRolPagoEnum.prestamosEmpresa,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el descuento por prestamos de la empresa',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Peluquería',
      formControlName: FormRolPagoEnum.peluqueria,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el valor',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Óptica',
      formControlName: FormRolPagoEnum.optica,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el valor',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Pago cuota vehículo',
      formControlName: FormRolPagoEnum.pagoCuotaVehiculo,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el pago de cuota vehículo',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Sueldo',
      formControlName: FormRolPagoEnum.sueldo,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el sueldo',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Bonificación',
      formControlName: FormRolPagoEnum.bonificacion,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese la bonificación',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Movilización especial',
      formControlName: FormRolPagoEnum.movilizacionEspecial,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese la movilización',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Componente salarial unificado',
      formControlName: FormRolPagoEnum.componenteSalarialUnif,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el componente salarial unificado',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Días falta',
      formControlName: FormRolPagoEnum.diasFalta,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese los días falta',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Días maternidad',
      formControlName: FormRolPagoEnum.diasMaternidad,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese los días de maternidad',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Días enfermedad',
      formControlName: FormRolPagoEnum.diasEnfermedad,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese los días de enfermedad',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Días vacación',
      formControlName: FormRolPagoEnum.diasVacacion,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese los días de vacación',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Horas atraso',
      formControlName: FormRolPagoEnum.horasAtraso,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese las horas de atraso',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Descuento maternidad',
      formControlName: FormRolPagoEnum.descuentoMaternidad,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el descuento maternidad',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Descuento enfermedad',
      formControlName: FormRolPagoEnum.descuentoEnfermedad,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el descuento enfermedad',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Descuento vacación',
      formControlName: FormRolPagoEnum.descuentoVacacion,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el descuento vacación',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Prov. décimo tercero',
      formControlName: FormRolPagoEnum.provDecimoTercero,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese prov. décimo tercero',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Prov. décimo cuarto',
      formControlName: FormRolPagoEnum.provDecimoCuarto,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese prov. décimo cuarto',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Prov. fondos reserva',
      formControlName: FormRolPagoEnum.provFondosReserva,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese prov. fondos reserva',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Prov. vacaciones',
      formControlName: FormRolPagoEnum.provVacaciones,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese prov. vacaciones',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Prov. aporte patronal',
      formControlName: FormRolPagoEnum.provAportePatronal,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese prov. aportePatronal',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Vacación 1',
      formControlName: FormRolPagoEnum.vacacion1,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese vacación 1',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Vacación 2',
      formControlName: FormRolPagoEnum.vacacion2,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese vacación 2',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Pago vacación ',
      formControlName: FormRolPagoEnum.pagoVacacion,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el pago vacación',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Pago fondo reserva mes ',
      formControlName: FormRolPagoEnum.pagoFondoReservaMes,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el pago fondo de reserva mes',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Pago décimo tercero cuarto mes ',
      formControlName: FormRolPagoEnum.pagoFondoReservaMes,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el pago décimo tercero cuarto mes',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Acumulado aporte personal iess',
      formControlName: FormRolPagoEnum.acumuladoAportePersonalIess,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el acumulado aporte personal IESS',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Acumulado décimo tercero',
      formControlName: FormRolPagoEnum.acumuladoDecimoTercero,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el acumulado décimo tercero',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Acumulado fondos reserva',
      formControlName: FormRolPagoEnum.acumuladoFondosReserva,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el acumulado fondos de reserva',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Acumulado vacaciones',
      formControlName: FormRolPagoEnum.acumuladoVacaciones,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el acumulado vacaciones',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Acumulado impuesto renta',
      formControlName: FormRolPagoEnum.acumuladoImpuestoRenta,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el acumulado impuesto renta',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Total ingresos',
      formControlName: FormRolPagoEnum.totalIngresos,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el total de ingresos',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Total egresos',
      formControlName: FormRolPagoEnum.totalEgresos,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el total de egresos',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Total a pagar',
      formControlName: FormRolPagoEnum.totalAPagar,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el total a pagar',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Otros ingresos',
      formControlName: FormRolPagoEnum.otrosIngresos,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese otros ingresos',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Prestamos IESS',
      formControlName: FormRolPagoEnum.prestamosIess,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese prestamos IESS',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },
    {
      type: fieldType.inputNumber,
      label: 'Total horas extra',
      formControlName: FormRolPagoEnum.totalHorasExtra,
      placeholder: 'Ej: 5',
      initialValue: "",
      help: 'Ingrese el total de horas extra',
      // patternMessage: REGEX_LETRAS_ESPACIOS.mensaje,
      validators: [
        // Validators.required,
        // Validators.pattern(REGEX_LETRAS_ESPACIOS.regex),
      ],
      inputNumber: {
        min: 0,
        minFractionDigits: 2,
        maxFractionDigits: 2
      },
      formGroup: new FormGroup({}),
      valid: false,
      column: '4',
      actualValue: '',
    },

  ]
  return arregloCampos;
}
