import {ModalidadContratoEnum} from '../../../../enums/modalidad-contrato';
import {GeneroEnum} from '../../../../enums/genero.enum';
import {SiNoEnum} from '../../../../enums/si-no.enum';

export interface TrabajadorUpdateDto {
  modalidadContrato?: ModalidadContratoEnum;
  estadoCivil?: string;
  genero?: GeneroEnum;
  grupoSanguineo?: string;
  nivelEstudios?: string;
  profesion?: string;
  direccionDomiciliaria?: string;
  estadoFamiliar?: string;
  sueldo?: number;
  bonificacion?: number;
  movilizacionEspecial?: number;
  componenteSalarialUnifi?: number;
  retencionesJudiciales?: number;
  polizaPersonal?: number;
  aporteIess?: SiNoEnum;
  aporteIessAsumido?: SiNoEnum;
  decimosAnio?: SiNoEnum;
  fondoReservaIess?: SiNoEnum;
  utilidades?: SiNoEnum;
  pagoFondosReservaMes?: SiNoEnum;
  impuestoRentaPatron?: SiNoEnum;
  vacaciones?: SiNoEnum;
  beneficios?: SiNoEnum;
  pagoDecTercerCuartoMes?: SiNoEnum;
  cuentaContableNombre?: string;
  acumuladoAportePersonalIess?: number;
  acumuladoDecimoTercero?: number;
  acumuladoFondosReserva?: number;
  acumuladoVacaciones?: number;
  acumuladoImpuestoRenta?: number;
  utilidadCargas?: number;
  tiempoParcial?: SiNoEnum;
  factorParcial?: number;
  pasante?: SiNoEnum;
  reingreso?: SiNoEnum;
  fechaReingreso?: string;
  provDecimoTercero?: number;
  provDecimoCuarto?: number;
  provFondosReserva?: number;
  provVacaciones?: number;
  provAportePatronal?: number;
  fechaIngreso?: string;
  decimoCuarto?: number;
}
